; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
monitor_rts = 0
monitor_dtr = 0
board_build.partitions = huge_app.csv
monitor_filters = esp32_exception_decoder
build_flags = 
	-Ofast
	-Wall
	-Wno-unknown-pragmas
	-Wno-write-strings
	'-D CORE_DEBUG_LEVEL=ARDUHAL_LOG_LEVEL_INFO'
lib_deps = 
	bblanchon/ArduinoJson@^7.0.3
	adafruit/Adafruit ADS1X15@^2.5.0
	xreef/PCF8575 library@^1.1.2
	
build_src_filter = 
	+<**/*.cpp>
	-<ui/**.*>

[env:lolin_c3_mini]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/53.03.11/platform-espressif32.zip
framework = arduino
board = lolin_c3_mini
monitor_speed = 115200
board_build.mcu = esp32c3
board_build.f_cpu = 160000000L
build_type = debug
lib_deps = 
	bblanchon/ArduinoJson@^7.0.3
	adafruit/Adafruit ADS1X15@^2.5.0
	xreef/PCF8575 library@^1.1.2
	adafruit/Adafruit NeoPixel@^1.12.3
;	JeepifyLib=symlink://../../Jeepify-Libraries
build_src_filter = 
	+<**/*.cpp>
	-<ui/**.*>
build_flags = 
	-D ARDUINO_USB_MODE=1
	-D ARDUINO_USB_CDC_ON_BOOT=1
	-Ofast
	-Wall
	-Wno-unknown-pragmas
	-Wno-write-strings
	'-D BOARD_NAME="${this.board}"'
	'-D CORE_DEBUG_LEVEL=ARDUHAL_LOG_LEVEL_INFO'

[env:s3-mini]
platform = espressif32
board = lolin_s3_mini
framework = arduino
monitor_speed = 115200
lib_deps = 
	bblanchon/ArduinoJson@^7.0.3
	adafruit/Adafruit ADS1X15@^2.5.0
	xreef/PCF8575 library@^1.1.2

build_src_filter = 
	+<**/*.cpp>
	-<ui/**.*>
build_flags = 
	-D ARDUINO_USB_MODE=1
	-D ARDUINO_USB_CDC_ON_BOOT=1
	-Ofast
	-Wall
	-Wno-unknown-pragmas
	-Wno-write-strings
	'-D BOARD_NAME="${this.board}"'
	'-D CORE_DEBUG_LEVEL=ARDUHAL_LOG_LEVEL_INFO'

[env:c3-noDispPortADS]
platform = espressif32
framework = arduino
board = seeed_xiao_esp32c3
monitor_speed = 460800
lib_deps = 
	bblanchon/ArduinoJson@^7.0.3
	adafruit/Adafruit ADS1X15@^2.5.0
	xreef/PCF8575 library@^1.1.2
	
build_src_filter = 
	+<**/*.cpp>
	-<ui/**.*>
build_flags = 
	-D ARDUINO_USB_MODE=1
	-D ARDUINO_USB_CDC_ON_BOOT=1
	-Ofast
	-Wall
	-Wno-unknown-pragmas
	-Wno-write-strings
	'-D BOARD_NAME="${this.board}"'
	'-D CORE_DEBUG_LEVEL=ARDUHAL_LOG_LEVEL_INFO'

[env:d1_wroom_02]
platform = espressif8266
board = esp8285
board_build.mcu = esp8266
board_build.f_cpu = 80000000L
framework = arduino
monitor_speed = 74880
monitor_rts = 0
monitor_dtr = 0
board_build.flash_mode = dout
upload_resetmethod = nodemcu
monitor_filters = esp8266_exception_decoder
build_flags = 
	-Ofast
	-Wall
	'-D BOARD_NAME="${this.board}"'
	'-D CORE_DEBUG_LEVEL=ARDUHAL_LOG_LEVEL_INFO'
	-Wno-unknown-pragmas
	-Wno-write-strings
lib_deps = 
	bblanchon/ArduinoJson@^7.0.3
	adafruit/Adafruit ADS1X15@^2.5.0
	xreef/PCF8575 library@^1.1.2
	vshymanskyy/Preferences@^2.1.0
	
build_src_filter = 
	+<**/*.cpp>
	-<ui/**.*>

[env:c6]
board = esp32-c6-devkitc-1
platform = espressif32
framework = arduino
monitor_speed = 460800
lib_deps = 
	bblanchon/ArduinoJson@^7.0.3
	adafruit/Adafruit ADS1X15@^2.5.0
	xreef/PCF8575 library@^1.1.2
	
build_src_filter = 
	+<**/*.cpp>
	-<ui/**.*>
build_flags = 
	-D ARDUINO_USB_MODE=1
	-D ARDUINO_USB_CDC_ON_BOOT=1
	-Ofast
	-Wall
	-Wno-unknown-pragmas
	-Wno-write-strings
	'-D BOARD_NAME="${this.board}"'
	'-D CORE_DEBUG_LEVEL=ARDUHAL_LOG_LEVEL_INFO'
