// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.2.0
// Project name: SquareLine_Project_Jeepify_Large_PDC

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void Ui_Init_Custom(lv_event_t * e);
void Ui_Menu_Loaded(lv_event_t * e);
void Ui_MenuBtn4_Click(lv_event_t * e);
void Ui_Settings_Loaded(lv_event_t * e);
void Ui_SettingBtn1_Click(lv_event_t * e);
void Ui_SettingBtn2_Click(lv_event_t * e);
void Ui_SettingBtn3_Click(lv_event_t * e);
void Ui_SettingBtn4_Click(lv_event_t * e);
void Ui_Settings_Reset(lv_event_t * e);
void Ui_Settings_Brightness_Changed(lv_event_t * e);
void Ui_GaugeSingle_Loaded(lv_event_t * e);
void Ui_GaugeSingle_Next(lv_event_t * e);
void Ui_GaugeSingle_Prev(lv_event_t * e);
void Ui_GaugeSingle_Leave(lv_event_t * e);
void Ui_Switch_Loaded(lv_event_t * e);
void Ui_Switch_Next(lv_event_t * e);
void UI_Switch_Prev(lv_event_t * e);
void Ui_Switch_Leave(lv_event_t * e);
void Ui_SwitchButton_Clicked(lv_event_t * e);
void Ui_Switch_SwitchButton_Long(lv_event_t * e);
void Ui_ChangeName_Next(lv_event_t * e);
void Ui_ChangeName_Prev(lv_event_t * e);
void Ui_ChangeName_Loaded(lv_event_t * e);
void Ui_ChangeName_Ready(lv_event_t * e);
void ui_Calib_Loaded(lv_event_t * e);
void Ui_Calib_Leave(lv_event_t * e);
void ui_Calib_Current_Click(lv_event_t * e);
void Ui_NumKey_Ready(lv_event_t * e);
void Ui_MultiGauge_Loaded(lv_event_t * e);
void Ui_GaugeMulti_Leave(lv_event_t * e);
void Ui_GaugeMulti_Gauge_Click(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
