// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.2.0
// Project name: SquareLine_Project_Jeepify_Large_PDC

#ifndef _SQUARELINE_PROJECT_JEEPIFY_LARGE_PDC_UI_COMP_HOOK_H
#define _SQUARELINE_PROJECT_JEEPIFY_LARGE_PDC_UI_COMP_HOOK_H

#ifdef __cplusplus
extern "C" {
#endif

void ui_comp_SwitchButton_create_hook(lv_obj_t * comp);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
