// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.2.0
// Project name: SquareLine_Project_Jeepify_Large_PDC

#include "../ui.h"


void ui_event_comp_SwitchButton_ImgButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    lv_obj_t ** comp_SwitchButton = lv_event_get_user_data(e);
    if(event_code == LV_EVENT_CLICKED) {
        Ui_SwitchButton_Clicked(e);
    }
}
void ui_event_comp_SwitchButton_LblSwitchPeriph(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    lv_obj_t ** comp_SwitchButton = lv_event_get_user_data(e);
    if(event_code == LV_EVENT_LONG_PRESSED) {
        Ui_Switch_SwitchButton_Long(e);
    }
}

// COMPONENT SwitchButton

lv_obj_t * ui_SwitchButton_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_SwitchButton;
    cui_SwitchButton = lv_obj_create(comp_parent);
    lv_obj_remove_style_all(cui_SwitchButton);
    lv_obj_set_width(cui_SwitchButton, 73);
    lv_obj_set_height(cui_SwitchButton, 197);
    lv_obj_set_x(cui_SwitchButton, -175);
    lv_obj_set_y(cui_SwitchButton, -50);
    lv_obj_set_align(cui_SwitchButton, LV_ALIGN_CENTER);
    lv_obj_clear_flag(cui_SwitchButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_ImgButton;
    cui_ImgButton = lv_imgbtn_create(cui_SwitchButton);
    lv_imgbtn_set_src(cui_ImgButton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_toggle_vertical_off_75_png, NULL);
    lv_imgbtn_set_src(cui_ImgButton, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_toggle_vertical_on_75_png, NULL);
    lv_imgbtn_set_src(cui_ImgButton, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui_img_toggle_vertical_off_75_png, NULL);
    lv_imgbtn_set_src(cui_ImgButton, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui_img_toggle_vertical_on_75_png, NULL);
    lv_obj_set_height(cui_ImgButton, 167);
    lv_obj_set_width(cui_ImgButton, LV_SIZE_CONTENT);   /// 1
    lv_obj_add_flag(cui_ImgButton, LV_OBJ_FLAG_CHECKABLE);     /// Flags

    lv_obj_t * cui_LblSwitchPeer;
    cui_LblSwitchPeer = lv_label_create(cui_SwitchButton);
    lv_obj_set_width(cui_LblSwitchPeer, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_LblSwitchPeer, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_LblSwitchPeer, 0);
    lv_obj_set_y(cui_LblSwitchPeer, 74);
    lv_obj_set_align(cui_LblSwitchPeer, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(cui_LblSwitchPeer, lv_color_hex(0x825E02), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_LblSwitchPeer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_LblSwitchPeriph;
    cui_LblSwitchPeriph = lv_label_create(cui_SwitchButton);
    lv_obj_set_width(cui_LblSwitchPeriph, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_LblSwitchPeriph, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_LblSwitchPeriph, 0);
    lv_obj_set_y(cui_LblSwitchPeriph, 50);
    lv_obj_set_align(cui_LblSwitchPeriph, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(cui_LblSwitchPeriph, lv_color_hex(0x825E02), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_LblSwitchPeriph, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_LblSwitchPeriph, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_LblSwitchId;
    cui_LblSwitchId = lv_label_create(cui_SwitchButton);
    lv_obj_set_width(cui_LblSwitchId, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_LblSwitchId, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_LblSwitchId, -2);
    lv_obj_set_y(cui_LblSwitchId, 15);
    lv_obj_set_align(cui_LblSwitchId, LV_ALIGN_CENTER);
    lv_label_set_text(cui_LblSwitchId, "Nr");

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_SWITCHBUTTON_NUM);
    children[UI_COMP_SWITCHBUTTON_SWITCHBUTTON] = cui_SwitchButton;
    children[UI_COMP_SWITCHBUTTON_IMGBUTTON] = cui_ImgButton;
    children[UI_COMP_SWITCHBUTTON_LBLSWITCHPEER] = cui_LblSwitchPeer;
    children[UI_COMP_SWITCHBUTTON_LBLSWITCHPERIPH] = cui_LblSwitchPeriph;
    children[UI_COMP_SWITCHBUTTON_LBLSWITCHID] = cui_LblSwitchId;
    lv_obj_add_event_cb(cui_SwitchButton, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_SwitchButton, del_component_child_event_cb, LV_EVENT_DELETE, children);
    lv_obj_add_event_cb(cui_ImgButton, ui_event_comp_SwitchButton_ImgButton, LV_EVENT_ALL, children);
    lv_obj_add_event_cb(cui_LblSwitchPeriph, ui_event_comp_SwitchButton_LblSwitchPeriph, LV_EVENT_ALL, children);
    ui_comp_SwitchButton_create_hook(cui_SwitchButton);
    return cui_SwitchButton;
}

