// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.2.0
// Project name: SquareLine_Project_Jeepify_Large_PDC

#ifndef _UI_COMP_SWITCHBUTTON_H
#define _UI_COMP_SWITCHBUTTON_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT SwitchButton
#define UI_COMP_SWITCHBUTTON_SWITCHBUTTON 0
#define UI_COMP_SWITCHBUTTON_IMGBUTTON 1
#define UI_COMP_SWITCHBUTTON_LBLSWITCHPEER 2
#define UI_COMP_SWITCHBUTTON_LBLSWITCHPERIPH 3
#define UI_COMP_SWITCHBUTTON_LBLSWITCHID 4
#define _UI_COMP_SWITCHBUTTON_NUM 5
lv_obj_t * ui_SwitchButton_create(lv_obj_t * comp_parent);
void ui_event_comp_SwitchButton_ImgButton(lv_event_t * e);
void ui_event_comp_SwitchButton_LblSwitchPeriph(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
