// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.2.0
// Project name: SquareLine_Project_Jeepify_Large_PDC

#include "../ui.h"

void ui_ScreenCalib_screen_init(void)
{
    ui_ScreenCalib = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenCalib, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_ScreenCalib, &ui_img_1825836894, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_ScreenCalib);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, 0);
    lv_obj_set_y(ui_Label7, -140);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "click to calibrate");
    lv_obj_set_style_text_color(ui_Label7, lv_color_hex(0xDBDBDB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label7, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_ScreenCalib);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, -73);
    lv_obj_set_y(ui_Label6, 122);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "make sure, no devices are \non the current-sensors");
    lv_obj_set_style_text_color(ui_Label6, lv_color_hex(0x825E02), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnCalibCurrent = lv_btn_create(ui_ScreenCalib);
    lv_obj_set_width(ui_BtnCalibCurrent, 213);
    lv_obj_set_height(ui_BtnCalibCurrent, 100);
    lv_obj_set_x(ui_BtnCalibCurrent, -100);
    lv_obj_set_y(ui_BtnCalibCurrent, -20);
    lv_obj_set_align(ui_BtnCalibCurrent, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnCalibCurrent, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnCalibCurrent, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnCalibCurrent, lv_color_hex(0x825E02), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnCalibCurrent, 100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblCalibCurrentValues = lv_label_create(ui_BtnCalibCurrent);
    lv_obj_set_width(ui_LblCalibCurrentValues, 74);
    lv_obj_set_height(ui_LblCalibCurrentValues, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_LblCalibCurrentValues, -62);
    lv_obj_set_y(ui_LblCalibCurrentValues, 0);
    lv_obj_set_align(ui_LblCalibCurrentValues, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblCalibCurrentValues, "(0A)\n(12A)\n(14A)\n99.9(A)");
    lv_obj_set_style_text_color(ui_LblCalibCurrentValues, lv_color_hex(0x825E02), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LblCalibCurrentValues, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LblCalibCurrentValues, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LblCalibCurrentValues, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_LblCalibCurrentValues, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_LblCalibCurrentValues, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_LblCalibCurrentValues, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_LblCalibCurrentValues, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblCalibCurrentNames = lv_label_create(ui_BtnCalibCurrent);
    lv_obj_set_width(ui_LblCalibCurrentNames, 121);
    lv_obj_set_height(ui_LblCalibCurrentNames, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_LblCalibCurrentNames, 30);
    lv_obj_set_y(ui_LblCalibCurrentNames, 0);
    lv_obj_set_align(ui_LblCalibCurrentNames, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblCalibCurrentNames, "(0A)\n(12A)\n(14A)\n17(A)");
    lv_obj_set_style_text_color(ui_LblCalibCurrentNames, lv_color_hex(0x825E02), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LblCalibCurrentNames, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LblCalibCurrentNames, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LblCalibCurrentNames, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_LblCalibCurrentNames, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_LblCalibCurrentNames, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_LblCalibCurrentNames, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_LblCalibCurrentNames, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnCalibVoltage = lv_btn_create(ui_ScreenCalib);
    lv_obj_set_width(ui_BtnCalibVoltage, 193);
    lv_obj_set_height(ui_BtnCalibVoltage, 100);
    lv_obj_set_x(ui_BtnCalibVoltage, 130);
    lv_obj_set_y(ui_BtnCalibVoltage, -23);
    lv_obj_set_align(ui_BtnCalibVoltage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnCalibVoltage, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnCalibVoltage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnCalibVoltage, lv_color_hex(0x825E02), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnCalibVoltage, 100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblCalibVoltage = lv_label_create(ui_BtnCalibVoltage);
    lv_obj_set_width(ui_LblCalibVoltage, 145);
    lv_obj_set_height(ui_LblCalibVoltage, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_align(ui_LblCalibVoltage, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblCalibVoltage, "--.-V");
    lv_obj_set_style_text_color(ui_LblCalibVoltage, lv_color_hex(0x825E02), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LblCalibVoltage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LblCalibVoltage, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LblCalibVoltage, &lv_font_montserrat_44, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_LblCalibVoltage, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_LblCalibVoltage, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_LblCalibVoltage, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_LblCalibVoltage, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_LblCalibCurrentValues, ui_event_LblCalibCurrentValues, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_LblCalibCurrentNames, ui_event_LblCalibCurrentNames, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnCalibCurrent, ui_event_BtnCalibCurrent, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_LblCalibVoltage, ui_event_LblCalibVoltage, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ScreenCalib, ui_event_ScreenCalib, LV_EVENT_ALL, NULL);

}
