// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.2.0
// Project name: SquareLine_Project_Jeepify_Large_PDC

#include "../ui.h"

void ui_ScreenGaugeMulti_screen_init(void)
{
    ui_ScreenGaugeMulti = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenGaugeMulti, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_ScreenGaugeMulti, &ui_img_1825836894, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblGaugeMultiPeer1 = lv_label_create(ui_ScreenGaugeMulti);
    lv_obj_set_width(ui_LblGaugeMultiPeer1, 100);
    lv_obj_set_height(ui_LblGaugeMultiPeer1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblGaugeMultiPeer1, -170);
    lv_obj_set_y(ui_LblGaugeMultiPeer1, -140);
    lv_obj_set_align(ui_LblGaugeMultiPeer1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblGaugeMultiPeer1, "LED_Bar");
    lv_obj_set_style_text_color(ui_LblGaugeMultiPeer1, lv_color_hex(0x825E02), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LblGaugeMultiPeer1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LblGaugeMultiPeer1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LblGaugeMultiPeer1, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblGaugeMultiPeer2 = lv_label_create(ui_ScreenGaugeMulti);
    lv_obj_set_width(ui_LblGaugeMultiPeer2, 100);
    lv_obj_set_height(ui_LblGaugeMultiPeer2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblGaugeMultiPeer2, -50);
    lv_obj_set_y(ui_LblGaugeMultiPeer2, -140);
    lv_obj_set_align(ui_LblGaugeMultiPeer2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblGaugeMultiPeer2, "LED_Bar");
    lv_obj_set_style_text_color(ui_LblGaugeMultiPeer2, lv_color_hex(0x825E02), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LblGaugeMultiPeer2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LblGaugeMultiPeer2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LblGaugeMultiPeer2, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblGaugeMultiPeer3 = lv_label_create(ui_ScreenGaugeMulti);
    lv_obj_set_width(ui_LblGaugeMultiPeer3, 100);
    lv_obj_set_height(ui_LblGaugeMultiPeer3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblGaugeMultiPeer3, 70);
    lv_obj_set_y(ui_LblGaugeMultiPeer3, -140);
    lv_obj_set_align(ui_LblGaugeMultiPeer3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblGaugeMultiPeer3, "LED_Bar");
    lv_obj_set_style_text_color(ui_LblGaugeMultiPeer3, lv_color_hex(0x825E02), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LblGaugeMultiPeer3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LblGaugeMultiPeer3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LblGaugeMultiPeer3, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblGaugeMultiPeer4 = lv_label_create(ui_ScreenGaugeMulti);
    lv_obj_set_width(ui_LblGaugeMultiPeer4, 100);
    lv_obj_set_height(ui_LblGaugeMultiPeer4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblGaugeMultiPeer4, -170);
    lv_obj_set_y(ui_LblGaugeMultiPeer4, 20);
    lv_obj_set_align(ui_LblGaugeMultiPeer4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblGaugeMultiPeer4, "LED_Bar");
    lv_obj_set_style_text_color(ui_LblGaugeMultiPeer4, lv_color_hex(0x825E02), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LblGaugeMultiPeer4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LblGaugeMultiPeer4, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LblGaugeMultiPeer4, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblGaugeMultiPeer5 = lv_label_create(ui_ScreenGaugeMulti);
    lv_obj_set_width(ui_LblGaugeMultiPeer5, 100);
    lv_obj_set_height(ui_LblGaugeMultiPeer5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblGaugeMultiPeer5, -50);
    lv_obj_set_y(ui_LblGaugeMultiPeer5, 20);
    lv_obj_set_align(ui_LblGaugeMultiPeer5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblGaugeMultiPeer5, "LED_Bar");
    lv_obj_set_style_text_color(ui_LblGaugeMultiPeer5, lv_color_hex(0x825E02), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LblGaugeMultiPeer5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LblGaugeMultiPeer5, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LblGaugeMultiPeer5, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblGaugeMultiValue1 = lv_label_create(ui_ScreenGaugeMulti);
    lv_obj_set_width(ui_LblGaugeMultiValue1, 100);
    lv_obj_set_height(ui_LblGaugeMultiValue1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblGaugeMultiValue1, -170);
    lv_obj_set_y(ui_LblGaugeMultiValue1, -20);
    lv_obj_set_align(ui_LblGaugeMultiValue1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblGaugeMultiValue1, "34.5 A");
    lv_obj_set_style_text_color(ui_LblGaugeMultiValue1, lv_color_hex(0x825E02), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LblGaugeMultiValue1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LblGaugeMultiValue1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LblGaugeMultiValue1, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblGaugeMultiValue2 = lv_label_create(ui_ScreenGaugeMulti);
    lv_obj_set_width(ui_LblGaugeMultiValue2, 100);
    lv_obj_set_height(ui_LblGaugeMultiValue2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblGaugeMultiValue2, -50);
    lv_obj_set_y(ui_LblGaugeMultiValue2, -20);
    lv_obj_set_align(ui_LblGaugeMultiValue2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblGaugeMultiValue2, "34.5 A");
    lv_obj_set_style_text_color(ui_LblGaugeMultiValue2, lv_color_hex(0x825E02), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LblGaugeMultiValue2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LblGaugeMultiValue2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LblGaugeMultiValue2, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblGaugeMultiValue3 = lv_label_create(ui_ScreenGaugeMulti);
    lv_obj_set_width(ui_LblGaugeMultiValue3, 100);
    lv_obj_set_height(ui_LblGaugeMultiValue3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblGaugeMultiValue3, 70);
    lv_obj_set_y(ui_LblGaugeMultiValue3, -20);
    lv_obj_set_align(ui_LblGaugeMultiValue3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblGaugeMultiValue3, "34.5 A");
    lv_obj_set_style_text_color(ui_LblGaugeMultiValue3, lv_color_hex(0x825E02), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LblGaugeMultiValue3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LblGaugeMultiValue3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LblGaugeMultiValue3, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblGaugeMultiValue4 = lv_label_create(ui_ScreenGaugeMulti);
    lv_obj_set_width(ui_LblGaugeMultiValue4, 100);
    lv_obj_set_height(ui_LblGaugeMultiValue4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblGaugeMultiValue4, -170);
    lv_obj_set_y(ui_LblGaugeMultiValue4, 140);
    lv_obj_set_align(ui_LblGaugeMultiValue4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblGaugeMultiValue4, "34.5 A");
    lv_obj_set_style_text_color(ui_LblGaugeMultiValue4, lv_color_hex(0x825E02), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LblGaugeMultiValue4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LblGaugeMultiValue4, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LblGaugeMultiValue4, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblGaugeMultiValue5 = lv_label_create(ui_ScreenGaugeMulti);
    lv_obj_set_width(ui_LblGaugeMultiValue5, 100);
    lv_obj_set_height(ui_LblGaugeMultiValue5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblGaugeMultiValue5, -50);
    lv_obj_set_y(ui_LblGaugeMultiValue5, 140);
    lv_obj_set_align(ui_LblGaugeMultiValue5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblGaugeMultiValue5, "34.5 A");
    lv_obj_set_style_text_color(ui_LblGaugeMultiValue5, lv_color_hex(0x825E02), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LblGaugeMultiValue5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LblGaugeMultiValue5, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LblGaugeMultiValue5, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblGaugeMultiType1 = lv_label_create(ui_ScreenGaugeMulti);
    lv_obj_set_width(ui_LblGaugeMultiType1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblGaugeMultiType1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblGaugeMultiType1, -170);
    lv_obj_set_y(ui_LblGaugeMultiType1, -85);
    lv_obj_set_align(ui_LblGaugeMultiType1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblGaugeMultiType1, "V");

    ui_LblGaugeMultiType2 = lv_label_create(ui_ScreenGaugeMulti);
    lv_obj_set_width(ui_LblGaugeMultiType2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblGaugeMultiType2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblGaugeMultiType2, -50);
    lv_obj_set_y(ui_LblGaugeMultiType2, -85);
    lv_obj_set_align(ui_LblGaugeMultiType2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblGaugeMultiType2, "V");

    ui_LblGaugeMultiType3 = lv_label_create(ui_ScreenGaugeMulti);
    lv_obj_set_width(ui_LblGaugeMultiType3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblGaugeMultiType3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblGaugeMultiType3, 70);
    lv_obj_set_y(ui_LblGaugeMultiType3, -85);
    lv_obj_set_align(ui_LblGaugeMultiType3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblGaugeMultiType3, "V");

    ui_LblGaugeMultiType4 = lv_label_create(ui_ScreenGaugeMulti);
    lv_obj_set_width(ui_LblGaugeMultiType4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblGaugeMultiType4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblGaugeMultiType4, -170);
    lv_obj_set_y(ui_LblGaugeMultiType4, 75);
    lv_obj_set_align(ui_LblGaugeMultiType4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblGaugeMultiType4, "V");

    ui_LblGaugeMultiType5 = lv_label_create(ui_ScreenGaugeMulti);
    lv_obj_set_width(ui_LblGaugeMultiType5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblGaugeMultiType5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblGaugeMultiType5, -50);
    lv_obj_set_y(ui_LblGaugeMultiType5, 75);
    lv_obj_set_align(ui_LblGaugeMultiType5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblGaugeMultiType5, "V");

    ui_BtnGaugeMultiGauge1 = lv_btn_create(ui_ScreenGaugeMulti);
    lv_obj_set_width(ui_BtnGaugeMultiGauge1, 100);
    lv_obj_set_height(ui_BtnGaugeMultiGauge1, 100);
    lv_obj_set_x(ui_BtnGaugeMultiGauge1, -170);
    lv_obj_set_y(ui_BtnGaugeMultiGauge1, -80);
    lv_obj_set_align(ui_BtnGaugeMultiGauge1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnGaugeMultiGauge1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnGaugeMultiGauge1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnGaugeMultiGauge1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnGaugeMultiGauge1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_BtnGaugeMultiGauge1, &ui_img_gauge_leer_100_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_BtnGaugeMultiGauge1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_BtnGaugeMultiGauge1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnGaugeMultiGauge2 = lv_btn_create(ui_ScreenGaugeMulti);
    lv_obj_set_width(ui_BtnGaugeMultiGauge2, 100);
    lv_obj_set_height(ui_BtnGaugeMultiGauge2, 100);
    lv_obj_set_x(ui_BtnGaugeMultiGauge2, -50);
    lv_obj_set_y(ui_BtnGaugeMultiGauge2, -80);
    lv_obj_set_align(ui_BtnGaugeMultiGauge2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnGaugeMultiGauge2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnGaugeMultiGauge2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnGaugeMultiGauge2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnGaugeMultiGauge2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_BtnGaugeMultiGauge2, &ui_img_gauge_leer_100_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_BtnGaugeMultiGauge2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_BtnGaugeMultiGauge2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnGaugeMultiGauge3 = lv_btn_create(ui_ScreenGaugeMulti);
    lv_obj_set_width(ui_BtnGaugeMultiGauge3, 100);
    lv_obj_set_height(ui_BtnGaugeMultiGauge3, 100);
    lv_obj_set_x(ui_BtnGaugeMultiGauge3, 70);
    lv_obj_set_y(ui_BtnGaugeMultiGauge3, -80);
    lv_obj_set_align(ui_BtnGaugeMultiGauge3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnGaugeMultiGauge3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnGaugeMultiGauge3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnGaugeMultiGauge3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnGaugeMultiGauge3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_BtnGaugeMultiGauge3, &ui_img_gauge_leer_100_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_BtnGaugeMultiGauge3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_BtnGaugeMultiGauge3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnGaugeMultiGauge4 = lv_btn_create(ui_ScreenGaugeMulti);
    lv_obj_set_width(ui_BtnGaugeMultiGauge4, 100);
    lv_obj_set_height(ui_BtnGaugeMultiGauge4, 100);
    lv_obj_set_x(ui_BtnGaugeMultiGauge4, -170);
    lv_obj_set_y(ui_BtnGaugeMultiGauge4, 80);
    lv_obj_set_align(ui_BtnGaugeMultiGauge4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnGaugeMultiGauge4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnGaugeMultiGauge4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnGaugeMultiGauge4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnGaugeMultiGauge4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_BtnGaugeMultiGauge4, &ui_img_gauge_leer_100_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_BtnGaugeMultiGauge4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_BtnGaugeMultiGauge4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnGaugeMultiGauge5 = lv_btn_create(ui_ScreenGaugeMulti);
    lv_obj_set_width(ui_BtnGaugeMultiGauge5, 100);
    lv_obj_set_height(ui_BtnGaugeMultiGauge5, 100);
    lv_obj_set_x(ui_BtnGaugeMultiGauge5, -50);
    lv_obj_set_y(ui_BtnGaugeMultiGauge5, 80);
    lv_obj_set_align(ui_BtnGaugeMultiGauge5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnGaugeMultiGauge5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnGaugeMultiGauge5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnGaugeMultiGauge5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnGaugeMultiGauge5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_BtnGaugeMultiGauge5, &ui_img_gauge_leer_100_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_BtnGaugeMultiGauge5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_BtnGaugeMultiGauge5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_BtnGaugeMultiGauge1, ui_event_BtnGaugeMultiGauge1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnGaugeMultiGauge2, ui_event_BtnGaugeMultiGauge2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnGaugeMultiGauge3, ui_event_BtnGaugeMultiGauge3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnGaugeMultiGauge4, ui_event_BtnGaugeMultiGauge4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnGaugeMultiGauge5, ui_event_BtnGaugeMultiGauge5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ScreenGaugeMulti, ui_event_ScreenGaugeMulti, LV_EVENT_ALL, NULL);

}
