// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.2.0
// Project name: SquareLine_Project_Jeepify_Large_PDC

#include "../ui.h"

void ui_ScrGaugeSingle_screen_init(void)
{
    ui_ScrGaugeSingle = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScrGaugeSingle, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_ScrGaugeSingle, &ui_img_1825836894, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgGaugeSingleGauge = lv_img_create(ui_ScrGaugeSingle);
    lv_img_set_src(ui_ImgGaugeSingleGauge, &ui_img_gauge_leer_240_png);
    lv_obj_set_width(ui_ImgGaugeSingleGauge, LV_SIZE_CONTENT);   /// 240
    lv_obj_set_height(ui_ImgGaugeSingleGauge, LV_SIZE_CONTENT);    /// 240
    lv_obj_set_x(ui_ImgGaugeSingleGauge, -87);
    lv_obj_set_y(ui_ImgGaugeSingleGauge, -11);
    lv_obj_set_align(ui_ImgGaugeSingleGauge, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImgGaugeSingleGauge, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImgGaugeSingleGauge, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LblGaugeSingleValueDescription = lv_label_create(ui_ScrGaugeSingle);
    lv_obj_set_width(ui_LblGaugeSingleValueDescription, 219);
    lv_obj_set_height(ui_LblGaugeSingleValueDescription, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblGaugeSingleValueDescription, 125);
    lv_obj_set_y(ui_LblGaugeSingleValueDescription, -118);
    lv_obj_set_align(ui_LblGaugeSingleValueDescription, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblGaugeSingleValueDescription, "LED-Bar");
    lv_obj_set_style_text_color(ui_LblGaugeSingleValueDescription, lv_color_hex(0x825E02), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LblGaugeSingleValueDescription, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LblGaugeSingleValueDescription, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LblGaugeSingleValueDescription, &lv_font_montserrat_44, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblGaugeSingleValue = lv_label_create(ui_ScrGaugeSingle);
    lv_obj_set_width(ui_LblGaugeSingleValue, 145);
    lv_obj_set_height(ui_LblGaugeSingleValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblGaugeSingleValue, 140);
    lv_obj_set_y(ui_LblGaugeSingleValue, -22);
    lv_obj_set_align(ui_LblGaugeSingleValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblGaugeSingleValue, "99.9V");
    lv_obj_set_style_text_color(ui_LblGaugeSingleValue, lv_color_hex(0x825E02), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LblGaugeSingleValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LblGaugeSingleValue, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LblGaugeSingleValue, &lv_font_montserrat_44, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_LblGaugeSingleValue, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LblGaugeSingleValue, lv_color_hex(0x825E02), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LblGaugeSingleValue, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_LblGaugeSingleValue, lv_color_hex(0x825E02), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_LblGaugeSingleValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_LblGaugeSingleValue, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_LblGaugeSingleValue, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_LblGaugeSingleValue, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_LblGaugeSingleValue, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_LblGaugeSingleValue, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_LblGaugeSingleValue, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblGaugeSingleType = lv_label_create(ui_ScrGaugeSingle);
    lv_obj_set_width(ui_LblGaugeSingleType, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblGaugeSingleType, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblGaugeSingleType, -85);
    lv_obj_set_y(ui_LblGaugeSingleType, -20);
    lv_obj_set_align(ui_LblGaugeSingleType, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblGaugeSingleType, "V");
    lv_obj_set_style_text_color(ui_LblGaugeSingleType, lv_color_hex(0x544A36), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LblGaugeSingleType, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LblGaugeSingleType, &lv_font_montserrat_44, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ScrGaugeSingle, ui_event_ScrGaugeSingle, LV_EVENT_ALL, NULL);

}
