// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.2.0
// Project name: SquareLine_Project_Jeepify_Large_PDC

#include "../ui.h"

void ui_ScrSwitch_screen_init(void)
{
    ui_ScrSwitch = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScrSwitch, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_ScrSwitch, &ui_img_1825836894, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SwitchButton1 = ui_SwitchButton_create(ui_ScrSwitch);
    lv_obj_set_x(ui_SwitchButton1, -175);
    lv_obj_set_y(ui_SwitchButton1, -50);




    ui_SwitchButton2 = ui_SwitchButton_create(ui_ScrSwitch);
    lv_obj_set_x(ui_SwitchButton2, -65);
    lv_obj_set_y(ui_SwitchButton2, -50);




    ui_SwitchButton3 = ui_SwitchButton_create(ui_ScrSwitch);
    lv_obj_set_x(ui_SwitchButton3, 45);
    lv_obj_set_y(ui_SwitchButton3, -50);




    ui_SwitchButton4 = ui_SwitchButton_create(ui_ScrSwitch);
    lv_obj_set_x(ui_SwitchButton4, 155);
    lv_obj_set_y(ui_SwitchButton4, -50);




    ui_ContainerSwitchValues = lv_obj_create(ui_ScrSwitch);
    lv_obj_remove_style_all(ui_ContainerSwitchValues);
    lv_obj_set_width(ui_ContainerSwitchValues, 208);
    lv_obj_set_height(ui_ContainerSwitchValues, 103);
    lv_obj_set_x(ui_ContainerSwitchValues, 36);
    lv_obj_set_y(ui_ContainerSwitchValues, 215);
    lv_obj_clear_flag(ui_ContainerSwitchValues, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LblGaugeSingleValueDescription1 = lv_label_create(ui_ContainerSwitchValues);
    lv_obj_set_width(ui_LblGaugeSingleValueDescription1, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_LblGaugeSingleValueDescription1, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_LblGaugeSingleValueDescription1, "LED-Bar");
    lv_obj_add_flag(ui_LblGaugeSingleValueDescription1, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_LblGaugeSingleValueDescription1, lv_color_hex(0x825E02),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LblGaugeSingleValueDescription1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LblGaugeSingleValueDescription1, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblGaugeSingleValueDescription2 = lv_label_create(ui_ContainerSwitchValues);
    lv_obj_set_width(ui_LblGaugeSingleValueDescription2, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_LblGaugeSingleValueDescription2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblGaugeSingleValueDescription2, 0);
    lv_obj_set_y(ui_LblGaugeSingleValueDescription2, 25);
    lv_label_set_text(ui_LblGaugeSingleValueDescription2, "LED-Bar");
    lv_obj_add_flag(ui_LblGaugeSingleValueDescription2, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_LblGaugeSingleValueDescription2, lv_color_hex(0x825E02),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LblGaugeSingleValueDescription2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LblGaugeSingleValueDescription2, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblGaugeSingleValueDescription3 = lv_label_create(ui_ContainerSwitchValues);
    lv_obj_set_width(ui_LblGaugeSingleValueDescription3, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_LblGaugeSingleValueDescription3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblGaugeSingleValueDescription3, 0);
    lv_obj_set_y(ui_LblGaugeSingleValueDescription3, 50);
    lv_label_set_text(ui_LblGaugeSingleValueDescription3, "LED-Bar");
    lv_obj_add_flag(ui_LblGaugeSingleValueDescription3, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_LblGaugeSingleValueDescription3, lv_color_hex(0x825E02),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LblGaugeSingleValueDescription3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LblGaugeSingleValueDescription3, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblGaugeSingleValueDescription4 = lv_label_create(ui_ContainerSwitchValues);
    lv_obj_set_width(ui_LblGaugeSingleValueDescription4, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_LblGaugeSingleValueDescription4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblGaugeSingleValueDescription4, 0);
    lv_obj_set_y(ui_LblGaugeSingleValueDescription4, 75);
    lv_label_set_text(ui_LblGaugeSingleValueDescription4, "LED-Bar");
    lv_obj_add_flag(ui_LblGaugeSingleValueDescription4, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_LblGaugeSingleValueDescription4, lv_color_hex(0x825E02),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LblGaugeSingleValueDescription4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LblGaugeSingleValueDescription4, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblGaugeSingleValue1 = lv_label_create(ui_ContainerSwitchValues);
    lv_obj_set_width(ui_LblGaugeSingleValue1, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_LblGaugeSingleValue1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblGaugeSingleValue1, 100);
    lv_obj_set_y(ui_LblGaugeSingleValue1, 0);
    lv_label_set_text(ui_LblGaugeSingleValue1, "18.35A");
    lv_obj_add_flag(ui_LblGaugeSingleValue1, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_LblGaugeSingleValue1, lv_color_hex(0x825E02), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LblGaugeSingleValue1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LblGaugeSingleValue1, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblGaugeSingleValue2 = lv_label_create(ui_ContainerSwitchValues);
    lv_obj_set_width(ui_LblGaugeSingleValue2, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_LblGaugeSingleValue2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblGaugeSingleValue2, 100);
    lv_obj_set_y(ui_LblGaugeSingleValue2, 25);
    lv_label_set_text(ui_LblGaugeSingleValue2, "18.35A");
    lv_obj_add_flag(ui_LblGaugeSingleValue2, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_LblGaugeSingleValue2, lv_color_hex(0x825E02), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LblGaugeSingleValue2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LblGaugeSingleValue2, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblGaugeSingleValue3 = lv_label_create(ui_ContainerSwitchValues);
    lv_obj_set_width(ui_LblGaugeSingleValue3, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_LblGaugeSingleValue3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblGaugeSingleValue3, 100);
    lv_obj_set_y(ui_LblGaugeSingleValue3, 50);
    lv_label_set_text(ui_LblGaugeSingleValue3, "18.35A");
    lv_obj_add_flag(ui_LblGaugeSingleValue3, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_LblGaugeSingleValue3, lv_color_hex(0x825E02), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LblGaugeSingleValue3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LblGaugeSingleValue3, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblGaugeSingleValue4 = lv_label_create(ui_ContainerSwitchValues);
    lv_obj_set_width(ui_LblGaugeSingleValue4, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_LblGaugeSingleValue4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblGaugeSingleValue4, 100);
    lv_obj_set_y(ui_LblGaugeSingleValue4, 75);
    lv_label_set_text(ui_LblGaugeSingleValue4, "18.35A");
    lv_obj_add_flag(ui_LblGaugeSingleValue4, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_LblGaugeSingleValue4, lv_color_hex(0x825E02), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LblGaugeSingleValue4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LblGaugeSingleValue4, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblSwitchPage = lv_label_create(ui_ScrSwitch);
    lv_obj_set_width(ui_LblSwitchPage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblSwitchPage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblSwitchPage, 213);
    lv_obj_set_y(ui_LblSwitchPage, 29);
    lv_obj_set_align(ui_LblSwitchPage, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblSwitchPage, "1");

    lv_obj_add_event_cb(ui_ScrSwitch, ui_event_ScrSwitch, LV_EVENT_ALL, NULL);

}
