// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.2.0
// Project name: SquareLine_Project_Jeepify_Large_PDC

#include "../ui.h"

void ui_ScrPeers_screen_init(void)
{
    ui_ScrPeers = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScrPeers, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_ScrPeers, &ui_img_1825836894, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RollerPeers = lv_roller_create(ui_ScrPeers);
    lv_roller_set_options(ui_RollerPeers, "Option 1\nOption 2\nOption 3", LV_ROLLER_MODE_INFINITE);
    lv_obj_set_height(ui_RollerPeers, 168);
    lv_obj_set_width(ui_RollerPeers, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_RollerPeers, 175);
    lv_obj_set_y(ui_RollerPeers, -56);
    lv_obj_set_align(ui_RollerPeers, LV_ALIGN_CENTER);

    ui_LblPeersPeerName = lv_label_create(ui_ScrPeers);
    lv_obj_set_width(ui_LblPeersPeerName, 277);
    lv_obj_set_height(ui_LblPeersPeerName, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblPeersPeerName, -40);
    lv_obj_set_y(ui_LblPeersPeerName, -138);
    lv_obj_set_align(ui_LblPeersPeerName, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblPeersPeerName, "PeerName");
    lv_obj_set_style_text_color(ui_LblPeersPeerName, lv_color_hex(0x825E02), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LblPeersPeerName, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LblPeersPeerName, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LblPeersPeerName, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblPeersPeerType = lv_label_create(ui_ScrPeers);
    lv_obj_set_width(ui_LblPeersPeerType, 207);
    lv_obj_set_height(ui_LblPeersPeerType, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblPeersPeerType, -40);
    lv_obj_set_y(ui_LblPeersPeerType, -109);
    lv_obj_set_align(ui_LblPeersPeerType, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblPeersPeerType, "PeerType");
    lv_obj_set_style_text_color(ui_LblPeersPeerType, lv_color_hex(0x825E02), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LblPeersPeerType, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LblPeersPeerType, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LblPeersPeerType, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnPeerCalibrate = lv_btn_create(ui_ScrPeers);
    lv_obj_set_width(ui_BtnPeerCalibrate, 50);
    lv_obj_set_height(ui_BtnPeerCalibrate, 50);
    lv_obj_set_x(ui_BtnPeerCalibrate, -193);
    lv_obj_set_y(ui_BtnPeerCalibrate, -54);
    lv_obj_set_align(ui_BtnPeerCalibrate, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnPeerCalibrate, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnPeerCalibrate, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnPeerCalibrate, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnPeerCalibrate, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_BtnPeerCalibrate, &ui_img_icon_calib_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BtnPeerCalibrate, lv_color_hex(0xC1851A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BtnPeerCalibrate, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BtnPeerCalibrate, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_BtnPeerCalibrate, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_BtnPeerCalibrate, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_BtnPeerCalibrate, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_BtnPeerCalibrate, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_BtnPeerCalibrate, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_BtnPeerCalibrate, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BtnPeerCalibrate, lv_color_hex(0x8B6729), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_BtnPeerCalibrate, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_img_src(ui_BtnPeerCalibrate, &ui_img_icon_pair_png, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_BtnMenu9 = lv_btn_create(ui_ScrPeers);
    lv_obj_set_width(ui_BtnMenu9, 50);
    lv_obj_set_height(ui_BtnMenu9, 50);
    lv_obj_set_x(ui_BtnMenu9, -191);
    lv_obj_set_y(ui_BtnMenu9, 11);
    lv_obj_set_align(ui_BtnMenu9, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnMenu9, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnMenu9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnMenu9, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnMenu9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_BtnMenu9, &ui_img_icon_keyboard_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BtnMenu9, lv_color_hex(0xC1851A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BtnMenu9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BtnMenu9, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_BtnMenu9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_BtnMenu9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_BtnMenu9, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_BtnMenu9, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_BtnMenu9, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_BtnMenu9, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BtnMenu9, lv_color_hex(0x8B6729), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_BtnMenu9, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_BtnMenu10 = lv_btn_create(ui_ScrPeers);
    lv_obj_set_width(ui_BtnMenu10, 50);
    lv_obj_set_height(ui_BtnMenu10, 50);
    lv_obj_set_x(ui_BtnMenu10, -190);
    lv_obj_set_y(ui_BtnMenu10, 79);
    lv_obj_set_align(ui_BtnMenu10, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnMenu10, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnMenu10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnMenu10, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnMenu10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_BtnMenu10, &ui_img_icon_pair_off_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BtnMenu10, lv_color_hex(0xC1851A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BtnMenu10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BtnMenu10, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_BtnMenu10, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_BtnMenu10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_BtnMenu10, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_BtnMenu10, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_BtnMenu10, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_BtnMenu10, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BtnMenu10, lv_color_hex(0x8B6729), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_BtnMenu10, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_img_src(ui_BtnMenu10, &ui_img_icon_pair_png, LV_PART_MAIN | LV_STATE_CHECKED);

    lv_obj_add_event_cb(ui_BtnPeerCalibrate, ui_event_BtnPeerCalibrate, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnMenu9, ui_event_BtnMenu9, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnMenu10, ui_event_BtnMenu10, LV_EVENT_ALL, NULL);

}
