// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.2.0
// Project name: SquareLine_Project_Jeepify_Large_PDC

#include "../ui.h"

void ui_ScrNumKey_screen_init(void)
{
    ui_ScrNumKey = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScrNumKey, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_ScrNumKey, &ui_img_1825836894, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Keyboard2 = lv_keyboard_create(ui_ScrNumKey);
    lv_keyboard_set_mode(ui_Keyboard2, LV_KEYBOARD_MODE_NUMBER);
    lv_obj_set_width(ui_Keyboard2, 289);
    lv_obj_set_height(ui_Keyboard2, 178);
    lv_obj_set_x(ui_Keyboard2, -66);
    lv_obj_set_y(ui_Keyboard2, -43);
    lv_obj_set_align(ui_Keyboard2, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_Keyboard2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Keyboard2, lv_color_hex(0x825E02), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Keyboard2, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Keyboard2, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Keyboard2, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Keyboard2, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Keyboard2, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label10 = lv_label_create(ui_ScrNumKey);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, -125);
    lv_obj_set_y(ui_Label10, 139);
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "enter actual voltage");
    lv_obj_set_style_text_color(ui_Label10, lv_color_hex(0x825E02), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TxtAreaScrNumKeyVoltage = lv_textarea_create(ui_ScrNumKey);
    lv_obj_set_width(ui_TxtAreaScrNumKeyVoltage, 122);
    lv_obj_set_height(ui_TxtAreaScrNumKeyVoltage, LV_SIZE_CONTENT);    /// 250
    lv_obj_set_x(ui_TxtAreaScrNumKeyVoltage, -69);
    lv_obj_set_y(ui_TxtAreaScrNumKeyVoltage, 89);
    lv_obj_set_align(ui_TxtAreaScrNumKeyVoltage, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TxtAreaScrNumKeyVoltage, "Voltage");
    lv_textarea_set_one_line(ui_TxtAreaScrNumKeyVoltage, true);
    lv_obj_set_style_text_color(ui_TxtAreaScrNumKeyVoltage, lv_color_hex(0x825E02), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TxtAreaScrNumKeyVoltage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_TxtAreaScrNumKeyVoltage, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TxtAreaScrNumKeyVoltage, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TxtAreaScrNumKeyVoltage, lv_color_hex(0x825E02), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TxtAreaScrNumKeyVoltage, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_TxtAreaScrNumKeyVoltage, lv_color_hex(0x825E02), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_TxtAreaScrNumKeyVoltage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);



    lv_keyboard_set_textarea(ui_Keyboard2, ui_TxtAreaScrNumKeyVoltage);
    lv_obj_add_event_cb(ui_Keyboard2, ui_event_Keyboard2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ScrNumKey, ui_event_ScrNumKey, LV_EVENT_ALL, NULL);

}
