// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.2.0
// Project name: SquareLine_Project_Jeepify_Large_PDC

#include "../ui.h"

void ui_ScrChangeName_screen_init(void)
{
    ui_ScrChangeName = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScrChangeName, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_ScrChangeName, &ui_img_1825836894, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Keyboard1 = lv_keyboard_create(ui_ScrChangeName);
    lv_obj_set_width(ui_Keyboard1, 433);
    lv_obj_set_height(ui_Keyboard1, 178);
    lv_obj_set_x(ui_Keyboard1, 2);
    lv_obj_set_y(ui_Keyboard1, -54);
    lv_obj_set_align(ui_Keyboard1, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_Keyboard1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Keyboard1, lv_color_hex(0x825E02), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Keyboard1, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Keyboard1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Keyboard1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Keyboard1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Keyboard1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TxtAreaChangeName = lv_textarea_create(ui_ScrChangeName);
    lv_obj_set_width(ui_TxtAreaChangeName, 261);
    lv_obj_set_height(ui_TxtAreaChangeName, LV_SIZE_CONTENT);    /// 250
    lv_obj_set_x(ui_TxtAreaChangeName, -79);
    lv_obj_set_y(ui_TxtAreaChangeName, 99);
    lv_obj_set_align(ui_TxtAreaChangeName, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(ui_TxtAreaChangeName, 20);
    lv_textarea_set_placeholder_text(ui_TxtAreaChangeName, "PeriphName");
    lv_textarea_set_one_line(ui_TxtAreaChangeName, true);
    lv_obj_set_style_text_color(ui_TxtAreaChangeName, lv_color_hex(0xF9D474), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TxtAreaChangeName, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_TxtAreaChangeName, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TxtAreaChangeName, lv_color_hex(0x825E02), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TxtAreaChangeName, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_TxtAreaChangeName, lv_color_hex(0x825E02), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_TxtAreaChangeName, 255, LV_PART_MAIN | LV_STATE_DEFAULT);



    lv_keyboard_set_textarea(ui_Keyboard1, ui_TxtAreaChangeName);
    lv_obj_add_event_cb(ui_Keyboard1, ui_event_Keyboard1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ScrChangeName, ui_event_ScrChangeName, LV_EVENT_ALL, NULL);

}
